export const routes = {
  HOME: "/",
  PROFILE: "/profile",
  // PROFILE_EVENTS: "/profile/events",
  // PROFILE_EVENT: "/profile/events/:id",
  ARTISTS: "/artists",
  DISCOVER: "/discover",
  EVENTS: "/discover/events",
  CURRENT: "/discover/current",
  LEARNING: "/learning",
  MY_EVENTS: "/profile/events",
  ADD_EVENT: "/profile/events/add",
  SIGN_IN: "/signin",
  SIGN_UP: "/signup",
  SUBSCRIPTIONS: "/subscriptions",
};
